# Generated by Django 5.0 on 2023-12-17 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='Title', max_length=64),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='Category', max_length=64),
        ),
    ]
